version: '2'
services:
        dsi-runtime-catalog:
                container_name: dsi-runtime-catalog
                image: $DSI_IMG
                command: ["/root/start.sh", "dsi-runtime-catalog"]

        dsi-runtime-container1:
                container_name: dsi-runtime-container1
                image: $DSI_IMG
                command: ["/root/start.sh", "dsi-runtime-container", "dsi-runtime-catalog"]
                ports:
                        - "9443:9443"
                depends_on:
                        - dsi-runtime-catalog

        dsi-runtime-container2:
                container_name: dsi-runtime-container2
                image: $DSI_IMG
                command: ["/root/start.sh", "dsi-runtime-container", "dsi-runtime-catalog"]
                ports:
                        - "9444:9443"
                depends_on:
                        - dsi-runtime-catalog

        dsi-runtime-container3:
                container_name: dsi-runtime-container3
                image: $DSI_IMG
                command: ["/root/start.sh", "dsi-runtime-container", "dsi-runtime-catalog"]
                ports:
                        - "9445:9443"
                depends_on:
                        - dsi-runtime-catalog

        dsi-runtime-inbound:
                container_name: dsi-runtime-inbound
                image: $DSI_IMG
                command: ["/root/start.sh", "dsi-runtime-inbound", "dsi-runtime-catalog"]
                ports:
                        - "9090:9080"
                        - "9450:9443"
                depends_on:
                        - dsi-runtime-catalog
                        - dsi-runtime-container1
                        - dsi-runtime-container2
                        - dsi-runtime-container3

        dsi-runtime-outbound:
                container_name: dsi-runtime-outbound
                image: $DSI_IMG
                command: ["/root/start.sh", "cisOutbound", "dsi-runtime-catalog"]
                ports:
                        - "9091:9080"
                        - "9451:9443"
                depends_on:
                        - dsi-runtime-catalog
                        - dsi-runtime-container1
                        - dsi-runtime-container2
                        - dsi-runtime-container3
