version: '2'
services:
        dsi-runtime-catalog:
                container_name: dsi-runtime-catalog
                image: "dsi-runtime"
                command: ["/root/start.sh", "cisCatalog"]

        dsi-runtime-container1:
                container_name: dsi-runtime-container1
                image: "dsi-runtime"
                command: ["/root/start.sh", "dsi-runtime-container", "dsi-runtime-catalog"]
                ports:
                        - "9443:9443"

        dsi-runtime-container2:
                container_name: dsi-runtime-container2
                image: "dsi-runtime"
                command: ["/root/start.sh", "dsi-runtime-container", "dsi-runtime-catalog"]
                ports:
                        - "9444:9443"

        dsi-runtime-container3:
                container_name: dsi-runtime-container3
                image: "dsi-runtime"
                command: ["/root/start.sh", "dsi-runtime-container", "dsi-runtime-catalog"]
                ports:
                        - "9445:9443"

        dsi-runtime-inbound:
                container_name: dsi-runtime-inbound
                image: "dsi-runtime"
                command: ["/root/start.sh", "cisInbound", "dsi-runtime-catalog"]
                ports:
                        - "9450:9443"

        dsi-runtime-outbound:
                container_name: dsi-runtime-outbound
                image: "dsi-runtime"
                command: ["/root/start.sh", "cisOutbound", "dsi-runtime-catalog"]
                ports:
                        - "9451:9443"
